
vscode:
  extensions:
    - redhat.java
    - redhat.fabric8-analytics
    - redhat.vscode-commons
    - tabnine.tabnine-vscode
    - redhat.vscode-xml
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
